name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-frontend:latest ./Client
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-frontend:latest \
                     ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-frontend:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-frontend:${{ github.sha }}

      # ---------- BACKEND ----------
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-backend:latest ./backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-backend:latest \
                     ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-backend:${{ github.sha }}

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-backend:${{ github.sha }}
